"""initial schema"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f8b3fbdbf76a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_correlation_created', 'audit_events', ['correlation_id', 'created_at'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_table('forecasts',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('horizon_seconds', sa.Integer(), nullable=False),
    sa.Column('p10', sa.Float(), nullable=False),
    sa.Column('p50', sa.Float(), nullable=False),
    sa.Column('p90', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('feature_schema_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_predictions_entity_created', 'predictions', ['entity_id', 'created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('slice_key', sa.String(length=1000), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('slice_key', sa.String(length=1000), nullable=False),
    sa.Column('active_key', sa.String(length=1100), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('affected_slice', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('hypothesis', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_incidents_active_key', 'incidents', ['active_key'], unique=True)
    op.create_table('sessions',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('asn', sa.String(length=100), nullable=True),
    sa.Column('device_class', sa.String(length=100), nullable=True),
    sa.Column('network_type', sa.String(length=50), nullable=True),
    sa.Column('cdn_edge_id', sa.String(length=100), nullable=True),
    sa.Column('abr_profile', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_event_started', 'sessions', ['event_id', 'started_at'], unique=False)
    op.create_index('uq_sessions_event_external', 'sessions', ['event_id', 'external_id'], unique=True)
    op.create_table('action_proposals',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_scope', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected_effect', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('policy_state', sa.String(length=30), nullable=False),
    sa.Column('policy_reasons', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_runs',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('workflow_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_snapshots',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('schema_version', sa.String(length=100), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=False),
    sa.Column('buffer_level_ms', sa.Integer(), nullable=False),
    sa.Column('rebuffer_duration_ms', sa.Integer(), nullable=False),
    sa.Column('throughput_kbps', sa.Integer(), nullable=False),
    sa.Column('rtt_ms', sa.Integer(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('packet_loss_pct', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_session_time', 'observations', ['session_id', 'observed_at'], unique=False)
    op.create_index('uq_observations_session_sequence', 'observations', ['session_id', 'sequence'], unique=True)
    op.create_table('action_executions',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column('simulated_result', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['action_proposals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_executions')
    op.drop_index('uq_observations_session_sequence', table_name='observations')
    op.drop_index('ix_observations_session_time', table_name='observations')
    op.drop_table('observations')
    op.drop_table('feature_snapshots')
    op.drop_table('agent_runs')
    op.drop_table('action_proposals')
    op.drop_index('uq_sessions_event_external', table_name='sessions')
    op.drop_index('ix_sessions_event_started', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('uq_incidents_active_key', table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('alerts')
    op.drop_index('ix_predictions_entity_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_audit_correlation_created', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###